#!/usr/bin/env node

'use strict';

const fs = require('fs');
const toml = require('@iarna/toml');

const INPUT = require('../src/plugins/factoids/facts.json');
const OUTPUT = {};

const RECENT_TIME = new Date(Date.UTC(2015, 0, 1, 0, 0, 0, 0));

function toISOString(value) {
	let timestamp = Number(RECENT_TIME);
	if (
		typeof value === 'string'
		&& (/^\d{4}-(?:[0]\d|1[0-2])-(?:[0-2]\d|3[01])$/).test(value)
	) {
		timestamp = Date.parse(value);
	} else if (
		typeof value === 'number'
		&& value > Number(RECENT_TIME)
		&& value < Date.now()
	) {
		timestamp = value;
	}

	return new Date(timestamp).toISOString();
}

function normalize(input) {
	if (!input) {
		return null;
	}

	const entry = {
		changes: input.changes || [],
		creator: input.creator || '',
		date: toISOString(input.date),
		editors: input.editors || [],
		popularity: input.popularity || 0,
		type: input.alias ? 'alias' : 'factoid',
		value: input.value || input.alias || null,
	};

	if (!entry.value) {
		return null;
	}

	entry.changes = entry.changes.map((change) => ({
		date: toISOString(change.date),
		editor: (change.editor || 'unknown').toLowerCase(),
		previous: change['old-value'],
		value: change['new-value'],
	}));

	// Sort with newest entries first
	entry.changes.sort((a, b) => b.date.localeCompare(a.date.localeCompare));

	return entry;
}

function run() {
	const entries = Object.entries(INPUT.factoids).sort((a, b) => a[0].localeCompare(b[0]));
	entries.forEach(([key, value]) => {
		const entry = normalize(value);

		if (entry) {
			OUTPUT[key] = entry;
		} else {
			console.error(`Invalid entry for ${key}: ${JSON.stringify(value)}`);
		}
	});

	const result = toml.stringify(OUTPUT);
	fs.writeFileSync('src/plugins/factoids/facts.toml', result);
}

run();
